export const COUNTRIES = [
  { code: 'AF', name: 'Afghanistan', dialCode: '+93', currency: 'AFN', symbol: '؋' },
  { code: 'AL', name: 'Albania', dialCode: '+355', currency: 'ALL', symbol: 'L' },
  { code: 'DZ', name: 'Algeria', dialCode: '+213', currency: 'DZD', symbol: 'دج' },
  { code: 'AD', name: 'Andorra', dialCode: '+376', currency: 'EUR', symbol: '€' },
  { code: 'AO', name: 'Angola', dialCode: '+244', currency: 'AOA', symbol: 'Kz' },
  { code: 'AG', name: 'Antigua and Barbuda', dialCode: '+1', currency: 'XCD', symbol: '$' },
  { code: 'AR', name: 'Argentina', dialCode: '+54', currency: 'ARS', symbol: '$' },
  { code: 'AM', name: 'Armenia', dialCode: '+374', currency: 'AMD', symbol: '֏' },
  { code: 'AW', name: 'Aruba', dialCode: '+297', currency: 'AWG', symbol: 'ƒ' },
  { code: 'AU', name: 'Australia', dialCode: '+61', currency: 'AUD', symbol: 'A$' },
  { code: 'AT', name: 'Austria', dialCode: '+43', currency: 'EUR', symbol: '€' },
  { code: 'AZ', name: 'Azerbaijan', dialCode: '+994', currency: 'AZN', symbol: '₼' },
  { code: 'BS', name: 'Bahamas', dialCode: '+1', currency: 'BSD', symbol: '$' },
  { code: 'BH', name: 'Bahrain', dialCode: '+973', currency: 'BHD', symbol: 'د.ب' },
  { code: 'BD', name: 'Bangladesh', dialCode: '+880', currency: 'BDT', symbol: '৳' },
  { code: 'BB', name: 'Barbados', dialCode: '+1', currency: 'BBD', symbol: '$' },
  { code: 'BY', name: 'Belarus', dialCode: '+375', currency: 'BYN', symbol: 'Br' },
  { code: 'BE', name: 'Belgium', dialCode: '+32', currency: 'EUR', symbol: '€' },
  { code: 'BZ', name: 'Belize', dialCode: '+501', currency: 'BZD', symbol: '$' },
  { code: 'BJ', name: 'Benin', dialCode: '+229', currency: 'XOF', symbol: 'CFA' },
  { code: 'BM', name: 'Bermuda', dialCode: '+1', currency: 'BMD', symbol: '$' },
  { code: 'BT', name: 'Bhutan', dialCode: '+975', currency: 'BTN', symbol: 'Nu.' },
  { code: 'BO', name: 'Bolivia', dialCode: '+591', currency: 'BOB', symbol: 'Bs.' },
  { code: 'BA', name: 'Bosnia and Herzegovina', dialCode: '+387', currency: 'BAM', symbol: 'KM' },
  { code: 'BW', name: 'Botswana', dialCode: '+267', currency: 'BWP', symbol: 'P' },
  { code: 'BR', name: 'Brazil', dialCode: '+55', currency: 'BRL', symbol: 'R$' },
  { code: 'BN', name: 'Brunei', dialCode: '+673', currency: 'BND', symbol: '$' },
  { code: 'BG', name: 'Bulgaria', dialCode: '+359', currency: 'BGN', symbol: 'лв' },
  { code: 'BF', name: 'Burkina Faso', dialCode: '+226', currency: 'XOF', symbol: 'CFA' },
  { code: 'BI', name: 'Burundi', dialCode: '+257', currency: 'BIF', symbol: 'Fr' },
  { code: 'CV', name: 'Cabo Verde', dialCode: '+238', currency: 'CVE', symbol: 'CVE' },
  { code: 'KH', name: 'Cambodia', dialCode: '+855', currency: 'KHR', symbol: '៛' },
  { code: 'CM', name: 'Cameroon', dialCode: '+237', currency: 'XAF', symbol: 'FCFA' },
  { code: 'CA', name: 'Canada', dialCode: '+1', currency: 'CAD', symbol: 'C$' },
  { code: 'KY', name: 'Cayman Islands', dialCode: '+1', currency: 'KYD', symbol: '$' },
  { code: 'CF', name: 'Central African Republic', dialCode: '+236', currency: 'XAF', symbol: 'FCFA' },
  { code: 'TD', name: 'Chad', dialCode: '+235', currency: 'XAF', symbol: 'FCFA' },
  { code: 'CL', name: 'Chile', dialCode: '+56', currency: 'CLP', symbol: '$' },
  { code: 'CN', name: 'China', dialCode: '+86', currency: 'CNY', symbol: '¥' },
  { code: 'CO', name: 'Colombia', dialCode: '+57', currency: 'COP', symbol: '$' },
  { code: 'KM', name: 'Comoros', dialCode: '+269', currency: 'KMF', symbol: 'Fr' },
  { code: 'CG', name: 'Congo', dialCode: '+242', currency: 'XAF', symbol: 'FCFA' },
  { code: 'CD', name: 'DR Congo', dialCode: '+243', currency: 'CDF', symbol: 'Fr' },
  { code: 'CR', name: 'Costa Rica', dialCode: '+506', currency: 'CRC', symbol: '₡' },
  { code: 'CI', name: 'Côte d’Ivoire', dialCode: '+225', currency: 'XOF', symbol: 'CFA' },
  { code: 'HR', name: 'Croatia', dialCode: '+385', currency: 'EUR', symbol: '€' },
  { code: 'CU', name: 'Cuba', dialCode: '+53', currency: 'CUP', symbol: '$' },
  { code: 'CW', name: 'Curaçao', dialCode: '+599', currency: 'ANG', symbol: 'ƒ' },
  { code: 'CY', name: 'Cyprus', dialCode: '+357', currency: 'EUR', symbol: '€' },
  { code: 'CZ', name: 'Czechia', dialCode: '+420', currency: 'CZK', symbol: 'Kč' },
  { code: 'DK', name: 'Denmark', dialCode: '+45', currency: 'DKK', symbol: 'kr' },
  { code: 'DJ', name: 'Djibouti', dialCode: '+253', currency: 'DJF', symbol: 'Fr' },
  { code: 'DM', name: 'Dominica', dialCode: '+1', currency: 'XCD', symbol: '$' },
  { code: 'DO', name: 'Dominican Republic', dialCode: '+1', currency: 'DOP', symbol: 'RD$' },
  { code: 'EC', name: 'Ecuador', dialCode: '+593', currency: 'USD', symbol: '$' },
  { code: 'EG', name: 'Egypt', dialCode: '+20', currency: 'EGP', symbol: 'E£' },
  { code: 'SV', name: 'El Salvador', dialCode: '+503', currency: 'USD', symbol: '$' },
  { code: 'GQ', name: 'Equatorial Guinea', dialCode: '+240', currency: 'XAF', symbol: 'FCFA' },
  { code: 'ER', name: 'Eritrea', dialCode: '+291', currency: 'ERN', symbol: 'Nfk' },
  { code: 'EE', name: 'Estonia', dialCode: '+372', currency: 'EUR', symbol: '€' },
  { code: 'SZ', name: 'Eswatini', dialCode: '+268', currency: 'SZL', symbol: 'L' },
  { code: 'ET', name: 'Ethiopia', dialCode: '+251', currency: 'ETB', symbol: 'Br' },
  { code: 'FJ', name: 'Fiji', dialCode: '+679', currency: 'FJD', symbol: '$' },
  { code: 'FI', name: 'Finland', dialCode: '+358', currency: 'EUR', symbol: '€' },
  { code: 'FR', name: 'France', dialCode: '+33', currency: 'EUR', symbol: '€' },
  { code: 'GA', name: 'Gabon', dialCode: '+241', currency: 'XAF', symbol: 'FCFA' },
  { code: 'GM', name: 'Gambia', dialCode: '+220', currency: 'GMD', symbol: 'D' },
  { code: 'GE', name: 'Georgia', dialCode: '+995', currency: 'GEL', symbol: '₾' },
  { code: 'DE', name: 'Germany', dialCode: '+49', currency: 'EUR', symbol: '€' },
  { code: 'GH', name: 'Ghana', dialCode: '+233', currency: 'GHS', symbol: '₵' },
  { code: 'GI', name: 'Gibraltar', dialCode: '+350', currency: 'GIP', symbol: '£' },
  { code: 'GR', name: 'Greece', dialCode: '+30', currency: 'EUR', symbol: '€' },
  { code: 'GD', name: 'Grenada', dialCode: '+1', currency: 'XCD', symbol: '$' },
  { code: 'GT', name: 'Guatemala', dialCode: '+502', currency: 'GTQ', symbol: 'Q' },
  { code: 'GN', name: 'Guinea', dialCode: '+224', currency: 'GNF', symbol: 'Fr' },
  { code: 'GW', name: 'Guinea-Bissau', dialCode: '+245', currency: 'XOF', symbol: 'CFA' },
  { code: 'GY', name: 'Guyana', dialCode: '+592', currency: 'GYD', symbol: '$' },
  { code: 'HT', name: 'Haiti', dialCode: '+509', currency: 'HTG', symbol: 'G' },
  { code: 'HN', name: 'Honduras', dialCode: '+504', currency: 'HNL', symbol: 'L' },
  { code: 'HK', name: 'Hong Kong', dialCode: '+852', currency: 'HKD', symbol: 'HK$' },
  { code: 'HU', name: 'Hungary', dialCode: '+36', currency: 'HUF', symbol: 'Ft' },
  { code: 'IS', name: 'Iceland', dialCode: '+354', currency: 'ISK', symbol: 'kr' },
  { code: 'IN', name: 'India', dialCode: '+91', currency: 'INR', symbol: '₹' },
  { code: 'ID', name: 'Indonesia', dialCode: '+62', currency: 'IDR', symbol: 'Rp' },
  { code: 'IR', name: 'Iran', dialCode: '+98', currency: 'IRR', symbol: '﷼' },
  { code: 'IQ', name: 'Iraq', dialCode: '+964', currency: 'IQD', symbol: 'ع.د' },
  { code: 'IE', name: 'Ireland', dialCode: '+353', currency: 'EUR', symbol: '€' },
  { code: 'IL', name: 'Israel', dialCode: '+972', currency: 'ILS', symbol: '₪' },
  { code: 'IT', name: 'Italy', dialCode: '+39', currency: 'EUR', symbol: '€' },
  { code: 'JM', name: 'Jamaica', dialCode: '+1', currency: 'JMD', symbol: '$' },
  { code: 'JP', name: 'Japan', dialCode: '+81', currency: 'JPY', symbol: '¥' },
  { code: 'JO', name: 'Jordan', dialCode: '+962', currency: 'JOD', symbol: 'د.أ' },
  { code: 'KZ', name: 'Kazakhstan', dialCode: '+7', currency: 'KZT', symbol: '₸' },
  { code: 'KE', name: 'Kenya', dialCode: '+254', currency: 'KES', symbol: 'KSh' },
  { code: 'KI', name: 'Kiribati', dialCode: '+686', currency: 'AUD', symbol: 'A$' },
  { code: 'XK', name: 'Kosovo', dialCode: '+383', currency: 'EUR', symbol: '€' },
  { code: 'KW', name: 'Kuwait', dialCode: '+965', currency: 'KWD', symbol: 'د.ك' },
  { code: 'KG', name: 'Kyrgyzstan', dialCode: '+996', currency: 'KGS', symbol: 'сом' },
  { code: 'LA', name: 'Laos', dialCode: '+856', currency: 'LAK', symbol: '₭' },
  { code: 'LV', name: 'Latvia', dialCode: '+371', currency: 'EUR', symbol: '€' },
  { code: 'LB', name: 'Lebanon', dialCode: '+961', currency: 'LBP', symbol: 'ل.ل' },
  { code: 'LS', name: 'Lesotho', dialCode: '+266', currency: 'LSL', symbol: 'L' },
  { code: 'LR', name: 'Liberia', dialCode: '+231', currency: 'LRD', symbol: '$' },
  { code: 'LY', name: 'Libya', dialCode: '+218', currency: 'LYD', symbol: 'ل.د' },
  { code: 'LI', name: 'Liechtenstein', dialCode: '+423', currency: 'CHF', symbol: 'CHF' },
  { code: 'LT', name: 'Lithuania', dialCode: '+370', currency: 'EUR', symbol: '€' },
  { code: 'LU', name: 'Luxembourg', dialCode: '+352', currency: 'EUR', symbol: '€' },
  { code: 'MO', name: 'Macau', dialCode: '+853', currency: 'MOP', symbol: 'P' },
  { code: 'MG', name: 'Madagascar', dialCode: '+261', currency: 'MGA', symbol: 'Ar' },
  { code: 'MW', name: 'Malawi', dialCode: '+265', currency: 'MWK', symbol: 'MK' },
  { code: 'MY', name: 'Malaysia', dialCode: '+60', currency: 'MYR', symbol: 'RM' },
  { code: 'MV', name: 'Maldives', dialCode: '+960', currency: 'MVR', symbol: 'MVR' },
  { code: 'ML', name: 'Mali', dialCode: '+223', currency: 'XOF', symbol: 'CFA' },
  { code: 'MT', name: 'Malta', dialCode: '+356', currency: 'EUR', symbol: '€' },
  { code: 'MH', name: 'Marshall Islands', dialCode: '+692', currency: 'USD', symbol: '$' },
  { code: 'MR', name: 'Mauritania', dialCode: '+222', currency: 'MRU', symbol: 'UM' },
  { code: 'MU', name: 'Mauritius', dialCode: '+230', currency: 'MUR', symbol: '₨' },
  { code: 'MX', name: 'Mexico', dialCode: '+52', currency: 'MXN', symbol: '$' },
  { code: 'FM', name: 'Micronesia', dialCode: '+691', currency: 'USD', symbol: '$' },
  { code: 'MD', name: 'Moldova', dialCode: '+373', currency: 'MDL', symbol: 'L' },
  { code: 'MC', name: 'Monaco', dialCode: '+377', currency: 'EUR', symbol: '€' },
  { code: 'MN', name: 'Mongolia', dialCode: '+976', currency: 'MNT', symbol: '₮' },
  { code: 'ME', name: 'Montenegro', dialCode: '+382', currency: 'EUR', symbol: '€' },
  { code: 'MA', name: 'Morocco', dialCode: '+212', currency: 'MAD', symbol: 'د.م' },
  { code: 'MZ', name: 'Mozambique', dialCode: '+258', currency: 'MZN', symbol: 'MT' },
  { code: 'MM', name: 'Myanmar', dialCode: '+95', currency: 'MMK', symbol: 'K' },
  { code: 'NA', name: 'Namibia', dialCode: '+264', currency: 'NAD', symbol: '$' },
  { code: 'NR', name: 'Nauru', dialCode: '+674', currency: 'AUD', symbol: 'A$' },
  { code: 'NP', name: 'Nepal', dialCode: '+977', currency: 'NPR', symbol: '₨' },
  { code: 'NL', name: 'Netherlands', dialCode: '+31', currency: 'EUR', symbol: '€' },
  { code: 'NZ', name: 'New Zealand', dialCode: '+64', currency: 'NZD', symbol: '$' },
  { code: 'NI', name: 'Nicaragua', dialCode: '+505', currency: 'NIO', symbol: 'C$' },
  { code: 'NE', name: 'Niger', dialCode: '+227', currency: 'XOF', symbol: 'CFA' },
  { code: 'NG', name: 'Nigeria', dialCode: '+234', currency: 'NGN', symbol: '₦' },
  { code: 'MK', name: 'North Macedonia', dialCode: '+389', currency: 'MKD', symbol: 'ден' },
  { code: 'NO', name: 'Norway', dialCode: '+47', currency: 'NOK', symbol: 'kr' },
  { code: 'OM', name: 'Oman', dialCode: '+968', currency: 'OMR', symbol: 'ر.ع' },
  { code: 'PK', name: 'Pakistan', dialCode: '+92', currency: 'PKR', symbol: '₨' },
  { code: 'PW', name: 'Palau', dialCode: '+680', currency: 'USD', symbol: '$' },
  { code: 'PS', name: 'Palestine', dialCode: '+970', currency: 'ILS', symbol: '₪' },
  { code: 'PA', name: 'Panama', dialCode: '+507', currency: 'PAB', symbol: 'B/.' },
  { code: 'PG', name: 'Papua New Guinea', dialCode: '+675', currency: 'PGK', symbol: 'K' },
  { code: 'PY', name: 'Paraguay', dialCode: '+595', currency: 'PYG', symbol: '₲' },
  { code: 'PE', name: 'Peru', dialCode: '+51', currency: 'PEN', symbol: 'S/' },
  { code: 'PH', name: 'Philippines', dialCode: '+63', currency: 'PHP', symbol: '₱' },
  { code: 'PL', name: 'Poland', dialCode: '+48', currency: 'PLN', symbol: 'zł' },
  { code: 'PT', name: 'Portugal', dialCode: '+351', currency: 'EUR', symbol: '€' },
  { code: 'QA', name: 'Qatar', dialCode: '+974', currency: 'QAR', symbol: 'ر.ق' },
  { code: 'RO', name: 'Romania', dialCode: '+40', currency: 'RON', symbol: 'lei' },
  { code: 'RU', name: 'Russia', dialCode: '+7', currency: 'RUB', symbol: '₽' },
  { code: 'RW', name: 'Rwanda', dialCode: '+250', currency: 'RWF', symbol: 'Fr' },
  { code: 'KN', name: 'Saint Kitts and Nevis', dialCode: '+1', currency: 'XCD', symbol: '$' },
  { code: 'LC', name: 'Saint Lucia', dialCode: '+1', currency: 'XCD', symbol: '$' },
  { code: 'VC', name: 'Saint Vincent and the Grenadines', dialCode: '+1', currency: 'XCD', symbol: '$' },
  { code: 'WS', name: 'Samoa', dialCode: '+685', currency: 'WST', symbol: 'T' },
  { code: 'SM', name: 'San Marino', dialCode: '+378', currency: 'EUR', symbol: '€' },
  { code: 'ST', name: 'São Tomé and Príncipe', dialCode: '+239', currency: 'STN', symbol: 'Db' },
  { code: 'SA', name: 'Saudi Arabia', dialCode: '+966', currency: 'SAR', symbol: '﷼' },
  { code: 'SN', name: 'Senegal', dialCode: '+221', currency: 'XOF', symbol: 'CFA' },
  { code: 'RS', name: 'Serbia', dialCode: '+381', currency: 'RSD', symbol: 'дин' },
  { code: 'SC', name: 'Seychelles', dialCode: '+248', currency: 'SCR', symbol: '₨' },
  { code: 'SL', name: 'Sierra Leone', dialCode: '+232', currency: 'SLL', symbol: 'Le' },
  { code: 'SG', name: 'Singapore', dialCode: '+65', currency: 'SGD', symbol: 'S$' },
  { code: 'SK', name: 'Slovakia', dialCode: '+421', currency: 'EUR', symbol: '€' },
  { code: 'SI', name: 'Slovenia', dialCode: '+386', currency: 'EUR', symbol: '€' },
  { code: 'SB', name: 'Solomon Islands', dialCode: '+677', currency: 'SBD', symbol: '$' },
  { code: 'SO', name: 'Somalia', dialCode: '+252', currency: 'SOS', symbol: 'Sh' },
  { code: 'ZA', name: 'South Africa', dialCode: '+27', currency: 'ZAR', symbol: 'R' },
  { code: 'KR', name: 'South Korea', dialCode: '+82', currency: 'KRW', symbol: '₩' },
  { code: 'SS', name: 'South Sudan', dialCode: '+211', currency: 'SSP', symbol: '£' },
  { code: 'ES', name: 'Spain', dialCode: '+34', currency: 'EUR', symbol: '€' },
  { code: 'LK', name: 'Sri Lanka', dialCode: '+94', currency: 'LKR', symbol: '₨' },
  { code: 'SD', name: 'Sudan', dialCode: '+249', currency: 'SDG', symbol: '£' },
  { code: 'SR', name: 'Suriname', dialCode: '+597', currency: 'SRD', symbol: '$' },
  { code: 'SE', name: 'Sweden', dialCode: '+46', currency: 'SEK', symbol: 'kr' },
  { code: 'CH', name: 'Switzerland', dialCode: '+41', currency: 'CHF', symbol: 'CHF' },
  { code: 'SY', name: 'Syria', dialCode: '+963', currency: 'SYP', symbol: 'ل.س' },
  { code: 'TW', name: 'Taiwan', dialCode: '+886', currency: 'TWD', symbol: 'NT$' },
  { code: 'TJ', name: 'Tajikistan', dialCode: '+992', currency: 'TJS', symbol: 'ЅМ' },
  { code: 'TZ', name: 'Tanzania', dialCode: '+255', currency: 'TZS', symbol: 'TSh' },
  { code: 'TH', name: 'Thailand', dialCode: '+66', currency: 'THB', symbol: '฿' },
  { code: 'TL', name: 'Timor-Leste', dialCode: '+670', currency: 'USD', symbol: '$' },
  { code: 'TG', name: 'Togo', dialCode: '+228', currency: 'XOF', symbol: 'CFA' },
  { code: 'TO', name: 'Tonga', dialCode: '+676', currency: 'TOP', symbol: 'T$' },
  { code: 'TT', name: 'Trinidad and Tobago', dialCode: '+1', currency: 'TTD', symbol: '$' },
  { code: 'TN', name: 'Tunisia', dialCode: '+216', currency: 'TND', symbol: 'د.ت' },
  { code: 'TR', name: 'Türkiye', dialCode: '+90', currency: 'TRY', symbol: '₺' },
  { code: 'TM', name: 'Turkmenistan', dialCode: '+993', currency: 'TMT', symbol: 'm' },
  { code: 'TV', name: 'Tuvalu', dialCode: '+688', currency: 'AUD', symbol: 'A$' },
  { code: 'UG', name: 'Uganda', dialCode: '+256', currency: 'UGX', symbol: 'USh' },
  { code: 'UA', name: 'Ukraine', dialCode: '+380', currency: 'UAH', symbol: '₴' },
  { code: 'AE', name: 'United Arab Emirates', dialCode: '+971', currency: 'AED', symbol: 'د.إ' },
  { code: 'GB', name: 'United Kingdom', dialCode: '+44', currency: 'GBP', symbol: '£' },
  { code: 'US', name: 'United States', dialCode: '+1', currency: 'USD', symbol: '$' },
  { code: 'UY', name: 'Uruguay', dialCode: '+598', currency: 'UYU', symbol: '$U' },
  { code: 'UZ', name: 'Uzbekistan', dialCode: '+998', currency: 'UZS', symbol: 'so’m' },
  { code: 'VU', name: 'Vanuatu', dialCode: '+678', currency: 'VUV', symbol: 'Vt' },
  { code: 'VA', name: 'Vatican City', dialCode: '+379', currency: 'EUR', symbol: '€' },
  { code: 'VE', name: 'Venezuela', dialCode: '+58', currency: 'VES', symbol: 'Bs.' },
  { code: 'VN', name: 'Vietnam', dialCode: '+84', currency: 'VND', symbol: '₫' },
  { code: 'YE', name: 'Yemen', dialCode: '+967', currency: 'YER', symbol: '﷼' },
  { code: 'ZM', name: 'Zambia', dialCode: '+260', currency: 'ZMW', symbol: 'K' },
  { code: 'ZW', name: 'Zimbabwe', dialCode: '+263', currency: 'ZWL', symbol: '$' },
]

export const DEFAULT_COUNTRY = 'IN'

const COUNTRY_BY_CODE = new Map(COUNTRIES.map((country) => [country.code, country]))

export function getCountryByCode(code = DEFAULT_COUNTRY) {
  return COUNTRY_BY_CODE.get((code || '').toUpperCase()) ?? COUNTRIES[0]
}

export function formatAmount(country, amount) {
  const value = Number(amount)
  try {
    return new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: country.currency,
    }).format(Number.isFinite(value) ? value : 0)
  } catch {
    return `${country.symbol}${amount || '0'}`
  }
}